[package]
name = "tsp"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 3

[features]
visualize = ["speedy2d"]

[dependencies]
rand = "0.8"
speedy2d = { version = "1.8", optional = true }
